// <auto-generated>
// Generated by ActionRegistryGenerator. Do not edit manually.
// </auto-generated>

using System;
using System.Collections.Generic;
using Cysharp.Threading.Tasks;
using VContainer.StateMachine;

public static partial class ActionRegistry
{
    public static readonly IReadOnlyList<Type> ActionTypes = new[]
    {
        typeof(SceneLoadedAction),
        typeof(YourAction1),
        typeof(YourAction2),
        typeof(YourAction3),
    };

    public static readonly IReadOnlyList<Type> LabelControllerTypes = new[]
    {
        typeof(YourActionLabelController),
    };

    public static readonly IReadOnlyList<Type> StateTypes = new[]
    {
        typeof(VContainer.StateMachine.TaskStartState),
    };

    private static readonly Dictionary<(Type actionType, string methodName), ActionMethodDelegate> WebCallableMethods = new()
    {
        { (typeof(YourAction1), nameof(YourAction1.SpawnLabelList)), (action, data) => ((YourAction1)action).SpawnLabelList(data) },
        { (typeof(YourAction3), nameof(YourAction3.ExpClearLabels)), (action, data) => ((YourAction3)action).ExpClearLabels() },
        { (typeof(YourAction3), nameof(YourAction3.ExpCreateLabel)), (action, data) => ((YourAction3)action).ExpCreateLabel(data) },
        { (typeof(YourAction3), nameof(YourAction3.ExpPing)), (action, data) => ((YourAction3)action).ExpPing() },
        { (typeof(YourAction3), nameof(YourAction3.ExpReceiveData)), (action, data) => ((YourAction3)action).ExpReceiveData(data) },
    };

    private static readonly Dictionary<(Type actionType, string methodName), ActionMethodDelegate> CallbackMethods = new()
    {
        { (typeof(YourAction1), nameof(YourAction1.SendCreateLabel)), (action, data) => ((YourAction1)action).SendCreateLabel(data) },
        { (typeof(YourAction3), nameof(YourAction3.ExpAfterPing)), (action, data) => ((YourAction3)action).ExpAfterPing(data) },
        { (typeof(YourAction3), nameof(YourAction3.ExpSendDataBack)), (action, data) => ((YourAction3)action).ExpSendDataBack(data) },
    };

    private static readonly Dictionary<(Type actionType, string methodName), SubscribeMethodDelegate> SubscribeMethods = new()
    {
    };

}
