#if UNITY_EDITOR
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Text;
using Cysharp.Threading.Tasks;
using UnityEditor;
using UnityEngine;
using UniVCon;
using UniVCon.StateMachine;

namespace UniVCon.Editor
{
    public static class ActionRegistryGenerator
    {
        public const string OutputPath = "Assets/Scripts/Runtime/Core/Actions/ActionRegistry.g.cs";
        private static readonly Encoding Utf8NoBom = new UTF8Encoding(false);

        public static void Generate()
        {
            WriteRegistry(refreshAssetDatabase: true);
            Debug.Log($"[ActionRegistryGenerator] Generated: {OutputPath}");
        }

        public static void GenerateSilently()
        {
            WriteRegistry(refreshAssetDatabase: false);
        }

        public static IReadOnlyList<string> RepairAndValidate()
        {
            var beforeGenerateErrors = ActionSystemValidator.Validate();
            if (beforeGenerateErrors.Count > 0)
                return beforeGenerateErrors;

            Generate();
            return ActionSystemValidator.Validate();
        }

        private static void WriteRegistry(bool refreshAssetDatabase)
        {
            string content;
            try
            {
                content = BuildSource();
            }
            catch (Exception e)
            {
                Debug.LogError($"[ActionRegistryGenerator] Generation failed. Writing safe fallback registry.\n{e}");
                content = BuildFallbackSource();
            }

            Directory.CreateDirectory(Path.GetDirectoryName(OutputPath));
            File.WriteAllText(OutputPath, content, Utf8NoBom);
            AssetDatabase.ImportAsset(OutputPath);

            if (refreshAssetDatabase)
                AssetDatabase.Refresh();
        }

        private static string BuildSource()
        {
            var actionTypes = FindLiveScriptTypes(t => typeof(IBaseAction).IsAssignableFrom(t));
            var labelControllerTypes = FindLiveScriptTypes(t => typeof(IActionLabelController).IsAssignableFrom(t));
            var stateTypes = FindLiveScriptTypes(t => typeof(IState).IsAssignableFrom(t));

            var configs = LoadActionConfigs();
            var webCallableMethods = new List<ActionMethodEntry>();
            var callbackMethods = new List<ActionMethodEntry>();
            var subscribeMethods = new List<SubscribeMethodEntry>();

            foreach (var config in configs)
            {
                var actionType = ResolveActionType(config, actionTypes);
                if (actionType == null)
                {
                    Debug.LogWarning($"[ActionRegistryGenerator] Skip config without live action type: {config.name}");
                    continue;
                }

                foreach (var bind in config.methodBinds)
                {
                    if (!bind.enableWebFunc)
                        continue;

                    if (!string.IsNullOrEmpty(bind.unityFuncName))
                        AddActionMethod(webCallableMethods, actionType, bind.unityFuncName, "WebCallableMethods");

                    if (bind.callBackEnable && !string.IsNullOrEmpty(bind.callBackFuncName))
                        AddActionMethod(callbackMethods, actionType, bind.callBackFuncName, "CallbackMethods");
                }

                foreach (var sub in config.subscribeBinds)
                {
                    if (!string.IsNullOrEmpty(sub.localMethodName))
                        AddSubscribeMethod(subscribeMethods, actionType, sub.localMethodName);
                }
            }

            return BuildRegistrySource(actionTypes, labelControllerTypes, stateTypes, webCallableMethods, callbackMethods, subscribeMethods);
        }

        private static string BuildRegistrySource(
            IReadOnlyList<Type> actionTypes,
            IReadOnlyList<Type> labelControllerTypes,
            IReadOnlyList<Type> stateTypes,
            IReadOnlyList<ActionMethodEntry> webCallableMethods,
            IReadOnlyList<ActionMethodEntry> callbackMethods,
            IReadOnlyList<SubscribeMethodEntry> subscribeMethods)
        {
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated>");
            sb.AppendLine("// Generated by ActionRegistryGenerator. Do not edit manually.");
            sb.AppendLine("// </auto-generated>");
            sb.AppendLine();
            sb.AppendLine("using System;");
            sb.AppendLine("using System.Collections.Generic;");
            sb.AppendLine("using Cysharp.Threading.Tasks;");
            sb.AppendLine("using UniVCon.StateMachine;");
            sb.AppendLine();
            sb.AppendLine("namespace UniVCon");
            sb.AppendLine("{");
            sb.AppendLine("public static partial class ActionRegistry");
            sb.AppendLine("{");
            AppendTypeList(sb, "ActionTypes", actionTypes);
            AppendTypeList(sb, "LabelControllerTypes", labelControllerTypes);
            AppendTypeList(sb, "StateTypes", stateTypes);
            AppendActionMethodDictionary(sb, "WebCallableMethods", webCallableMethods);
            AppendActionMethodDictionary(sb, "CallbackMethods", callbackMethods);
            AppendSubscribeMethodDictionary(sb, "SubscribeMethods", subscribeMethods);
            sb.AppendLine("}");
            sb.AppendLine("}");
            return sb.ToString();
        }

        private static string BuildFallbackSource()
        {
            return BuildRegistrySource(
                Array.Empty<Type>(),
                Array.Empty<Type>(),
                Array.Empty<Type>(),
                Array.Empty<ActionMethodEntry>(),
                Array.Empty<ActionMethodEntry>(),
                Array.Empty<SubscribeMethodEntry>());
        }

        private static List<Type> FindLiveScriptTypes(Func<Type, bool> predicate)
        {
            return AssetDatabase.FindAssets("t:MonoScript")
                .Select(AssetDatabase.GUIDToAssetPath)
                .Where(IsRuntimeScriptPath)
                .Select(AssetDatabase.LoadAssetAtPath<MonoScript>)
                .Where(script => script != null)
                .Select(script => script.GetClass())
                .Where(type => type != null && type.IsClass && !type.IsAbstract && predicate(type))
                .Distinct()
                .OrderBy(type => type.FullName, StringComparer.Ordinal)
                .ToList();
        }

        private static bool IsRuntimeScriptPath(string path)
        {
            var normalized = path.Replace('\\', '/');
            return !normalized.Contains("/Editor/", StringComparison.OrdinalIgnoreCase) &&
                   !normalized.Contains("/Tests/Editor/", StringComparison.OrdinalIgnoreCase);
        }

        private static List<ActionConfigSO> LoadActionConfigs()
        {
            return AssetDatabase.FindAssets("t:ActionConfigSO")
                .Select(AssetDatabase.GUIDToAssetPath)
                .Select(AssetDatabase.LoadAssetAtPath<ActionConfigSO>)
                .Where(config => config != null)
                .OrderBy(config => config.name, StringComparer.Ordinal)
                .ToList();
        }

        private static Type ResolveActionType(ActionConfigSO config, IReadOnlyList<Type> actionTypes)
        {
            var scriptType = GetTargetActionScriptType(config);
            if (scriptType != null)
            {
                return actionTypes.Contains(scriptType) ? scriptType : null;
            }

            if (string.IsNullOrEmpty(config.targetActionClassName))
                return null;

            return actionTypes.FirstOrDefault(t =>
                t.Name == config.targetActionClassName ||
                t.FullName == config.targetActionClassName);
        }

        private static Type GetTargetActionScriptType(ActionConfigSO config)
        {
            var serializedConfig = new SerializedObject(config);
            var targetScript = serializedConfig.FindProperty("targetActionScript");
            return (targetScript?.objectReferenceValue as MonoScript)?.GetClass();
        }

        private static void AddActionMethod(List<ActionMethodEntry> entries, Type actionType, string methodName, string groupName)
        {
            var method = actionType.GetMethod(methodName, BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic);
            if (!IsValidActionMethod(method))
            {
                Debug.LogWarning($"[ActionRegistryGenerator] Skip {groupName}: {actionType.Name}.{methodName} must return UniTask and accept zero parameters or one object parameter.");
                return;
            }

            if (entries.Any(e => e.ActionType == actionType && e.MethodName == methodName))
                return;

            entries.Add(new ActionMethodEntry(actionType, method));
        }

        private static void AddSubscribeMethod(List<SubscribeMethodEntry> entries, Type actionType, string methodName)
        {
            var method = actionType.GetMethod(methodName, BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic);
            if (!IsValidSubscribeMethod(method))
            {
                Debug.LogWarning($"[ActionRegistryGenerator] Skip SubscribeMethods: {actionType.Name}.{methodName} must return UniTask and accept ActionMethodExecutedMessage or object.");
                return;
            }

            if (entries.Any(e => e.ActionType == actionType && e.MethodName == methodName))
                return;

            entries.Add(new SubscribeMethodEntry(actionType, method));
        }

        private static bool IsValidActionMethod(MethodInfo method)
        {
            if (method == null || method.ReturnType != typeof(UniTask))
                return false;

            var parameters = method.GetParameters();
            return parameters.Length == 0 ||
                   (parameters.Length == 1 && parameters[0].ParameterType == typeof(object));
        }

        private static bool IsValidSubscribeMethod(MethodInfo method)
        {
            if (method == null || method.ReturnType != typeof(UniTask))
                return false;

            var parameters = method.GetParameters();
            return parameters.Length == 0 ||
                   (parameters.Length == 1 && (parameters[0].ParameterType == typeof(ActionMethodExecutedMessage) ||
                                               parameters[0].ParameterType == typeof(object)));
        }

        private static void AppendTypeList(StringBuilder sb, string name, IReadOnlyList<Type> types)
        {
            sb.AppendLine($"    public static readonly IReadOnlyList<Type> {name} = new[]");
            sb.AppendLine("    {");
            foreach (var type in types)
            {
                sb.AppendLine($"        typeof({GetTypeName(type)}),");
            }
            sb.AppendLine("    };");
            sb.AppendLine();
        }

        private static void AppendActionMethodDictionary(StringBuilder sb, string name, IReadOnlyList<ActionMethodEntry> entries)
        {
            sb.AppendLine($"    private static readonly Dictionary<(Type actionType, string methodName), ActionMethodDelegate> {name} = new()");
            sb.AppendLine("    {");
            foreach (var entry in entries.OrderBy(e => e.ActionType.FullName, StringComparer.Ordinal).ThenBy(e => e.MethodName, StringComparer.Ordinal))
            {
                var typeName = GetTypeName(entry.ActionType);
                var args = entry.AcceptsData ? "data" : string.Empty;
                sb.AppendLine($"        {{ (typeof({typeName}), nameof({typeName}.{entry.MethodName})), (action, data) => (({typeName})action).{entry.MethodName}({args}) }},");
            }
            sb.AppendLine("    };");
            sb.AppendLine();
        }

        private static void AppendSubscribeMethodDictionary(StringBuilder sb, string name, IReadOnlyList<SubscribeMethodEntry> entries)
        {
            sb.AppendLine($"    private static readonly Dictionary<(Type actionType, string methodName), SubscribeMethodDelegate> {name} = new()");
            sb.AppendLine("    {");
            foreach (var entry in entries.OrderBy(e => e.ActionType.FullName, StringComparer.Ordinal).ThenBy(e => e.MethodName, StringComparer.Ordinal))
            {
                var typeName = GetTypeName(entry.ActionType);
                var args = entry.ParameterKind switch
                {
                    SubscribeParameterKind.Message => "message",
                    SubscribeParameterKind.Data => "message.Data",
                    _ => string.Empty
                };
                sb.AppendLine($"        {{ (typeof({typeName}), nameof({typeName}.{entry.MethodName})), (listener, message) => (({typeName})listener).{entry.MethodName}({args}) }},");
            }
            sb.AppendLine("    };");
            sb.AppendLine();
        }

        private static string GetTypeName(Type type)
        {
            if (type.IsGenericType)
                throw new NotSupportedException($"Generic type is not supported in ActionRegistry: {type.FullName}");

            return string.IsNullOrEmpty(type.Namespace)
                ? type.Name
                : $"{type.Namespace}.{type.Name}";
        }

        private sealed class ActionMethodEntry
        {
            public Type ActionType { get; }
            public MethodInfo Method { get; }
            public string MethodName => Method.Name;
            public bool AcceptsData => Method.GetParameters().Length == 1;

            public ActionMethodEntry(Type actionType, MethodInfo method)
            {
                ActionType = actionType;
                Method = method;
            }
        }

        private sealed class SubscribeMethodEntry
        {
            public Type ActionType { get; }
            public MethodInfo Method { get; }
            public string MethodName => Method.Name;
            public SubscribeParameterKind ParameterKind { get; }

            public SubscribeMethodEntry(Type actionType, MethodInfo method)
            {
                ActionType = actionType;
                Method = method;

                var parameters = method.GetParameters();
                if (parameters.Length == 0)
                    ParameterKind = SubscribeParameterKind.None;
                else if (parameters[0].ParameterType == typeof(ActionMethodExecutedMessage))
                    ParameterKind = SubscribeParameterKind.Message;
                else
                    ParameterKind = SubscribeParameterKind.Data;
            }
        }

        private enum SubscribeParameterKind
        {
            None,
            Message,
            Data
        }
    }
}
#endif
