#if UNITY_EDITOR
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Text;
using Cysharp.Threading.Tasks;
using UnityEditor;
using UnityEngine;
using VContainer.StateMachine;

namespace ActionSystem.Editor
{
    public static class ActionRegistryGenerator
    {
        private const string OutputPath = "Assets/Scripts/Core/Action/ActionRegistry.g.cs";

        public static void Generate()
        {
            string content = BuildSource();
            File.WriteAllText(OutputPath, content, Encoding.UTF8);
            AssetDatabase.ImportAsset(OutputPath);
            AssetDatabase.Refresh();
            Debug.Log($"[ActionRegistryGenerator] Generated: {OutputPath}");
        }

        public static void GenerateSilently()
        {
            string content = BuildSource();
            File.WriteAllText(OutputPath, content, Encoding.UTF8);
            AssetDatabase.ImportAsset(OutputPath);
        }

        private static string BuildSource()
        {
            var actionTypes = FindTypes(t => typeof(IBaseAction).IsAssignableFrom(t));
            var handlerTypes = FindTypes(t => typeof(IActionMsgHandler).IsAssignableFrom(t));
            var labelControllerTypes = FindTypes(t => typeof(IActionLabelController).IsAssignableFrom(t));
            var stateTypes = FindTypes(t => typeof(IState).IsAssignableFrom(t));

            var configs = LoadActionConfigs();
            var webCallableMethods = new List<ActionMethodEntry>();
            var callbackMethods = new List<ActionMethodEntry>();
            var subscribeMethods = new List<SubscribeMethodEntry>();

            foreach (var config in configs)
            {
                Type actionType = ResolveActionType(config, actionTypes);
                if (actionType == null)
                {
                    Debug.LogWarning($"[ActionRegistryGenerator] Skip config without action type: {config.name}");
                    continue;
                }

                foreach (var bind in config.methodBinds)
                {
                    if (!bind.enableWebFunc)
                        continue;

                    if (!string.IsNullOrEmpty(bind.unityFuncName))
                    {
                        AddActionMethod(webCallableMethods, actionType, bind.unityFuncName, "WebCallableMethods");
                    }

                    if (bind.callBackEnable && !string.IsNullOrEmpty(bind.callBackFuncName))
                    {
                        AddActionMethod(callbackMethods, actionType, bind.callBackFuncName, "CallbackMethods");
                    }
                }

                foreach (var sub in config.subscribeBinds)
                {
                    if (string.IsNullOrEmpty(sub.localMethodName))
                        continue;

                    AddSubscribeMethod(subscribeMethods, actionType, sub.localMethodName);
                }
            }

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated>");
            sb.AppendLine("// Generated by ActionRegistryGenerator. Do not edit manually.");
            sb.AppendLine("// </auto-generated>");
            sb.AppendLine();
            sb.AppendLine("using System;");
            sb.AppendLine("using System.Collections.Generic;");
            sb.AppendLine("using Cysharp.Threading.Tasks;");
            sb.AppendLine("using VContainer.StateMachine;");
            sb.AppendLine();
            sb.AppendLine("public static partial class ActionRegistry");
            sb.AppendLine("{");
            AppendTypeList(sb, "ActionTypes", actionTypes);
            AppendTypeList(sb, "HandlerTypes", handlerTypes);
            AppendTypeList(sb, "LabelControllerTypes", labelControllerTypes);
            AppendTypeList(sb, "StateTypes", stateTypes);
            AppendActionMethodDictionary(sb, "WebCallableMethods", webCallableMethods);
            AppendActionMethodDictionary(sb, "CallbackMethods", callbackMethods);
            AppendSubscribeMethodDictionary(sb, "SubscribeMethods", subscribeMethods);
            sb.AppendLine("}");
            return sb.ToString();
        }

        private static List<Type> FindTypes(Func<Type, bool> predicate)
        {
            return AppDomain.CurrentDomain.GetAssemblies()
                .SelectMany(GetLoadableTypes)
                .Where(t => t.IsClass && !t.IsAbstract && predicate(t))
                .OrderBy(t => t.FullName, StringComparer.Ordinal)
                .ToList();
        }

        private static IEnumerable<Type> GetLoadableTypes(Assembly assembly)
        {
            try
            {
                return assembly.GetTypes();
            }
            catch (ReflectionTypeLoadException e)
            {
                return e.Types.Where(t => t != null);
            }
        }

        private static List<ActionConfigSO> LoadActionConfigs()
        {
            return AssetDatabase.FindAssets("t:ActionConfigSO")
                .Select(AssetDatabase.GUIDToAssetPath)
                .Select(AssetDatabase.LoadAssetAtPath<ActionConfigSO>)
                .Where(config => config != null)
                .OrderBy(config => config.name, StringComparer.Ordinal)
                .ToList();
        }

        private static Type ResolveActionType(ActionConfigSO config, IReadOnlyList<Type> actionTypes)
        {
            if (string.IsNullOrEmpty(config.targetActionClassName))
                return null;

            return actionTypes.FirstOrDefault(t =>
                t.Name == config.targetActionClassName ||
                t.FullName == config.targetActionClassName);
        }

        private static void AddActionMethod(List<ActionMethodEntry> entries, Type actionType, string methodName, string groupName)
        {
            var method = actionType.GetMethod(methodName, BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic);
            if (!IsValidActionMethod(method))
            {
                Debug.LogWarning($"[ActionRegistryGenerator] Skip {groupName}: {actionType.Name}.{methodName} must return UniTask and accept zero parameters or one object parameter.");
                return;
            }

            if (entries.Any(e => e.ActionType == actionType && e.MethodName == methodName))
                return;

            entries.Add(new ActionMethodEntry(actionType, method));
        }

        private static void AddSubscribeMethod(List<SubscribeMethodEntry> entries, Type actionType, string methodName)
        {
            var method = actionType.GetMethod(methodName, BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic);
            if (!IsValidSubscribeMethod(method))
            {
                Debug.LogWarning($"[ActionRegistryGenerator] Skip SubscribeMethods: {actionType.Name}.{methodName} must return UniTask and accept ActionMethodExecutedMessage or object.");
                return;
            }

            if (entries.Any(e => e.ActionType == actionType && e.MethodName == methodName))
                return;

            entries.Add(new SubscribeMethodEntry(actionType, method));
        }

        private static bool IsValidActionMethod(MethodInfo method)
        {
            if (method == null || method.ReturnType != typeof(UniTask))
                return false;

            var parameters = method.GetParameters();
            return parameters.Length == 0 ||
                   (parameters.Length == 1 && parameters[0].ParameterType == typeof(object));
        }

        private static bool IsValidSubscribeMethod(MethodInfo method)
        {
            if (method == null || method.ReturnType != typeof(UniTask))
                return false;

            var parameters = method.GetParameters();
            return parameters.Length == 0 ||
                   (parameters.Length == 1 && (parameters[0].ParameterType == typeof(ActionMethodExecutedMessage) ||
                                               parameters[0].ParameterType == typeof(object)));
        }

        private static void AppendTypeList(StringBuilder sb, string name, IReadOnlyList<Type> types)
        {
            sb.AppendLine($"    public static readonly IReadOnlyList<Type> {name} = new[]");
            sb.AppendLine("    {");
            foreach (var type in types)
            {
                sb.AppendLine($"        typeof({GetTypeName(type)}),");
            }
            sb.AppendLine("    };");
            sb.AppendLine();
        }

        private static void AppendActionMethodDictionary(StringBuilder sb, string name, IReadOnlyList<ActionMethodEntry> entries)
        {
            sb.AppendLine($"    private static readonly Dictionary<(Type actionType, string methodName), ActionMethodDelegate> {name} = new()");
            sb.AppendLine("    {");
            foreach (var entry in entries.OrderBy(e => e.ActionType.FullName, StringComparer.Ordinal).ThenBy(e => e.MethodName, StringComparer.Ordinal))
            {
                string typeName = GetTypeName(entry.ActionType);
                string args = entry.AcceptsData ? "data" : string.Empty;
                sb.AppendLine($"        {{ (typeof({typeName}), nameof({typeName}.{entry.MethodName})), (action, data) => (({typeName})action).{entry.MethodName}({args}) }},");
            }
            sb.AppendLine("    };");
            sb.AppendLine();
        }

        private static void AppendSubscribeMethodDictionary(StringBuilder sb, string name, IReadOnlyList<SubscribeMethodEntry> entries)
        {
            sb.AppendLine($"    private static readonly Dictionary<(Type actionType, string methodName), SubscribeMethodDelegate> {name} = new()");
            sb.AppendLine("    {");
            foreach (var entry in entries.OrderBy(e => e.ActionType.FullName, StringComparer.Ordinal).ThenBy(e => e.MethodName, StringComparer.Ordinal))
            {
                string typeName = GetTypeName(entry.ActionType);
                string args = entry.ParameterKind switch
                {
                    SubscribeParameterKind.Message => "message",
                    SubscribeParameterKind.Data => "message.Data",
                    _ => string.Empty
                };
                sb.AppendLine($"        {{ (typeof({typeName}), nameof({typeName}.{entry.MethodName})), (listener, message) => (({typeName})listener).{entry.MethodName}({args}) }},");
            }
            sb.AppendLine("    };");
            sb.AppendLine();
        }

        private static string GetTypeName(Type type)
        {
            if (type.IsGenericType)
                throw new NotSupportedException($"Generic type is not supported in ActionRegistry: {type.FullName}");

            return string.IsNullOrEmpty(type.Namespace)
                ? type.Name
                : $"{type.Namespace}.{type.Name}";
        }

        private sealed class ActionMethodEntry
        {
            public Type ActionType { get; }
            public MethodInfo Method { get; }
            public string MethodName => Method.Name;
            public bool AcceptsData => Method.GetParameters().Length == 1;

            public ActionMethodEntry(Type actionType, MethodInfo method)
            {
                ActionType = actionType;
                Method = method;
            }
        }

        private sealed class SubscribeMethodEntry
        {
            public Type ActionType { get; }
            public MethodInfo Method { get; }
            public string MethodName => Method.Name;
            public SubscribeParameterKind ParameterKind { get; }

            public SubscribeMethodEntry(Type actionType, MethodInfo method)
            {
                ActionType = actionType;
                Method = method;

                var parameters = method.GetParameters();
                if (parameters.Length == 0)
                    ParameterKind = SubscribeParameterKind.None;
                else if (parameters[0].ParameterType == typeof(ActionMethodExecutedMessage))
                    ParameterKind = SubscribeParameterKind.Message;
                else
                    ParameterKind = SubscribeParameterKind.Data;
            }
        }

        private enum SubscribeParameterKind
        {
            None,
            Message,
            Data
        }
    }
}
#endif
