// <auto-generated>
// Generated by ActionRegistryGenerator. Do not edit manually.
// </auto-generated>

using System;
using System.Collections.Generic;
using Cysharp.Threading.Tasks;
using UniVCon.StateMachine;

namespace UniVCon
{
public static partial class ActionRegistry
{
    public static readonly IReadOnlyList<Type> ActionTypes = new[]
    {
        typeof(UniVCon.SceneLoadedAction),
        typeof(UniVCon.YourAction1),
        typeof(UniVCon.YourAction2),
        typeof(UniVCon.YourAction3),
    };

    public static readonly IReadOnlyList<Type> LabelControllerTypes = new[]
    {
        typeof(UniVCon.YourActionLabelController),
    };

    public static readonly IReadOnlyList<Type> StateTypes = new[]
    {
        typeof(UniVCon.StateMachine.TaskStartState),
    };

    private static readonly Dictionary<(Type actionType, string methodName), ActionMethodDelegate> WebCallableMethods = new()
    {
        { (typeof(UniVCon.YourAction1), nameof(UniVCon.YourAction1.SpawnLabelList)), (action, data) => ((UniVCon.YourAction1)action).SpawnLabelList(data) },
        { (typeof(UniVCon.YourAction3), nameof(UniVCon.YourAction3.ExpClearLabels)), (action, data) => ((UniVCon.YourAction3)action).ExpClearLabels() },
        { (typeof(UniVCon.YourAction3), nameof(UniVCon.YourAction3.ExpCreateLabel)), (action, data) => ((UniVCon.YourAction3)action).ExpCreateLabel(data) },
        { (typeof(UniVCon.YourAction3), nameof(UniVCon.YourAction3.ExpPing)), (action, data) => ((UniVCon.YourAction3)action).ExpPing() },
        { (typeof(UniVCon.YourAction3), nameof(UniVCon.YourAction3.ExpReceiveData)), (action, data) => ((UniVCon.YourAction3)action).ExpReceiveData(data) },
    };

    private static readonly Dictionary<(Type actionType, string methodName), ActionMethodDelegate> CallbackMethods = new()
    {
        { (typeof(UniVCon.YourAction1), nameof(UniVCon.YourAction1.SendCreateLabel)), (action, data) => ((UniVCon.YourAction1)action).SendCreateLabel(data) },
        { (typeof(UniVCon.YourAction3), nameof(UniVCon.YourAction3.ExpAfterPing)), (action, data) => ((UniVCon.YourAction3)action).ExpAfterPing(data) },
        { (typeof(UniVCon.YourAction3), nameof(UniVCon.YourAction3.ExpSendDataBack)), (action, data) => ((UniVCon.YourAction3)action).ExpSendDataBack(data) },
    };

    private static readonly Dictionary<(Type actionType, string methodName), SubscribeMethodDelegate> SubscribeMethods = new()
    {
    };

}
}
